# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzEXYucQyIMFKFa8D_f954xBVPiGZ-DK
"""

x = int(input("Enter the value of x:  "))
y = int(input("Enter the value of y:  "))
r = pow(x, y)
print("Result = ", r)